ARG NODE_VERSION=24.12.0-alpine

FROM node:${NODE_VERSION} AS dev

WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json ./
COPY apps/client ./apps/client
COPY packages ./packages

RUN pnpm install

RUN pnpm build

EXPOSE 5173

CMD ["pnpm", "run", "dev"]