ARG NODE_VERSION=24.12.0-alpine
FROM node:${NODE_VERSION}

WORKDIR /app

RUN npm install -g pnpm prisma turbo

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json ./

COPY apps/api ./apps/api
COPY packages ./packages

RUN pnpm install

RUN turbo run build

RUN turbo run generate

WORKDIR /app

EXPOSE 8000

CMD ["pnpm", "run", "docker"]